# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Emanuel', :city => cities.first)


Podcast.create(:id => 1, :title => "The Only Podcast on the Internet", :slug => "onlypodcast", :url => "http://theonlypodcastontheinternet.com", :description => "The Only Podcast on the Internet is an interview-style show featuring people involved in interested projects, usually categorized under the giant umbrella of \"Art\". Hosted by Don Denton.", :keywords => "Don Denton, other things", :explicit => false, :category => "Art", :subcategories => "Performance, Design", :author => "Don Denton")

AdminUser.create(:id => 2, :first => "Don", :last => "Denton", :username => "donny", :hashed_password => "0592fb7281b57c54bd78bd2d5343f0216d975425", :salt => "ba8d61cdee85116754b355c2cde36211b7907caa")

Episode.create(:id => 1, :title => "Disco Jesus Saves", :number => 1, :date => "Fri, 07 Jun 2013 16:00:00 UTC +00:00", :show_notes => "<h4>Sponsor: <a target=\"_blank\" href=\"http://mrkrisrogers.com\">Kris Rogers Bass and Photography</a></h4>\r\n<p>Kris is a musician and photographer based out of Astoria, NY. His work (both on the bass and behind the lens) is stellar. If you need a bass player or a photographer and you live in the NYC area, look no further.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://dondentonactor.com\">DonDentonActor.com</a></h4>\r\n<p>Don Denton's personal website with information about his acting career.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://vaughnirving.com\">VaughnIrving.com</a></h4>\r\n<p>Vaughn's personal website with information about his acting career.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://capitalfringe.org\">CapitalFringe.org</a></h4>\r\n<p>The DC Capital Fringe Festival is where Vaughn's show, <em>Disco Jesus and the Apostles of Funk</em>, will be performed.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://facebook.com/discojesusandtheapostlesoffunk\">Disco Jesus Facebook Page</a></h4>\r\n<p>Save yourself some typing time by using this link. Vaughn would really appreciate it if you \"like\" Disco Jesus.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://facebook.com/discojesusandtheapostlesoffunk/info\">Disco Jesus Cast and Show Information</a></h4>\r\n<p>The about section of the Facebook page is the best place, currently, to get information about the show.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://twitter.com/discojesussaves\">Disco Jesus on Twitter</a></h4>\r\n\r\n<h4><a target=\"_blank\" href=\"http://dondenton.com\">dondenton.com</a></h4>\r\n<p>This isn't Don's site. Well, it is, but a different Don Denton. One who... hosts... trivia? As of today, it hasn't been <em>actually</em> updated in about 6 or 7 years. At least there is a helpful link to DonDentonActor.com at the bottom.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://www.paulforeman.com\">Paul Foreman's Website</a></h4>\r\n<p>This is the guy who wrote <em>Bloodstains in Paradise</em>. The Paul Foreman who co-wrote the music for <em>Disco Jesus and the Apostles of Funk</em> is a different Paul Foreman. He's not <a target=\"_blank\" href=\"http://en.wikipedia.org/wiki/Paul_Foreman\">this Paul Foreman</a>, either.</p>", :file_name => "topcoti-1.mp3", :file_size => 23805382, :duration => "1:06:08", :art_name => "topcoti-1.jpg", :description => "Don Denton interviews Vaughn Matthew Irving about his upcoming Captital Fringe Festival show, <em>Disco Jesus on the Apostles of Funk</em>. Get a little insight into the rigors and rewards of creating and producing a brand new, actor-musician musical.", :keywords => "art, theatre, Disco Jesus and the Apostles of Funk, funk, creativity, writing, producing, Capital Fringe Festival, Don Denton, Vaughn Irving", :podcast_id => 1)
Episode.create(:id => 3, :title => "Empty Grave: Daddy's Little Girl", :number => 2, :date => "Mon, 01 Jul 2013 16:00:00 UTC +00:00", :show_notes => "<h4>Sponsor: <a target=\"_blank\" href=\"http://mrkrisrogers.com\">Kris Rogers Bass and Photography</a></h4>\r\n<p>Kris is a musician and photographer based out of Astoria, NY. His work (both on the bass and behind the lens) is stellar. If you need a bass player or a photographer and you live in the NYC area, look no further.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://emptygravecomic.com\">EmptyGraveComic.com</a></h4>\r\n<p>The best place to find information about <em>Empty Grave</em>.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"https://www.facebook.com/EmptyGraveDLG\">Empty Grave on Facebook</a></h4>\r\n<p>The best place to find information about <em>Empty Grave</em>... on Facebook.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://dondentonactor.com\">DonDentonActor.com</a></h4>\r\n<p>Don Denton's personal website with information about his acting career.</p>\r\n\r\n<h4><a target=\"_blank\" href=\"http://www.warwickjohnson.com\">WarwickJohnson.com</a></h4>\r\n<p>Warwick's personal site where he doens't really have time to review movies but does write other things.</p>\r\n", :file_name => "topcoti-2.mp3", :file_size => 23916077, :duration => "1:02:40", :art_name => "topcoti-2.jpg", :description => "Don Denton interviews Warwick (the second \"w\" is silent) Johnson about his soon-to-be-released comic book, \"Empty Grave: Daddy's Little Girl\".", :keywords => "art, comics, Empty Grave: Daddy's Little Girl, spaghetti western, creativity, writing, Don Denton, Warwick Johnson", :podcast_id => 1)
